
version: 2

sources:
  - name: feld-m-case
    schema: raw
    tables:
      - name: categories
      - name: customers
      - name: employees
      - name: order_details
      - name: orders
      - name: products
      - name: shippers